### ISSUE TITLE
Can't build due to undefined ciphers

### ISSUE THREAD

**Issue by TheHackerDev** [yanc0/beeping#14]
I believe that the TLS ciphers being used are dependent on version of openSSL being used on the operating system. In my case, it appears that I don't have support for a number of the ciphers, so it won't build or run properly without them. I'm running OSX v10.12.4 (latest of Sierra). Others may have issue depending on their particular operating system and version of openSSL (if that's indeed the library that is being used by `crypto/tls`).

<img width="723" alt="undefined ciphers on build" src="https://cloud.githubusercontent.com/assets/2362857/25847686/06cbfd86-34af-11e7-89df-8df9eab4170f.png">

**Comment by TheHackerDev** [comment]
Here are the set of ciphers that finally allowed me to successfully build (from the `tlscheck.go` file):

<img width="829" alt="allowed ciphers" src="https://cloud.githubusercontent.com/assets/2362857/25847880/d57c408c-34af-11e7-9b5a-d150b0add049.png">

Note: the little red arrows on the left side of the image show where I removed lines. This should help you identify where in the long list of ciphers needed to be removed in my case.

**Comment by yanc0** [comment]
Hi Aaron,

What is the Go version do you use? I'm using 1.8 on travis and my Debian Stretch.

**Comment by TheHackerDev** [comment]
go version go1.7.1 darwin/amd64 on OSX v10.12.4 (Sierra).

That might be why. I had heard of a number of issues with Go on this exact version of Sierra recently, that's why I didn't want to upgrade quite yet. Though they may be resolved now, I'll have to check.

**Comment by TheHackerDev** [comment]
Just checked, looked like 1.8.1 fixes these issues (https://github.com/golang/go/issues/19734#issuecomment-293221337). I'll upgrade and try again, then let you know on here. Going to have to head out for a bit right now though, so it may be a little bit later.

**Comment by TheHackerDev** [comment]
Just upgraded to go 1.8.1. Confirmed that this fixes it. This isn't on the main README yet, it might be a good idea to mention on the [Build](https://github.com/yanc0/beeping#build) section that the build has been confirmed to work on the latest version of Go (1.8.1). This might also be something that you can have automated with Travis CI, but I don't know for sure.

**Comment by yanc0** [comment]
https://github.com/yanc0/beeping#build

I've added the requirement on README.md

Thanks Aaron !

**Comment by TheHackerDev** [comment]
No problem! By the way, "#14" on the README doesn't have a link attached to it (I guess that only works within issues and PRs on GitHub). I understand that it means issue 14, but some may not. Maybe include a link to this issue directly?
