### ISSUE TITLE
Json compatibility

### ISSUE THREAD

**Issue by QuentinDeSoete** [yanc0/beeping#2]
When I send a json in python it look like this : 
{"url": "url.example.com", "insecure": "true", "timeout": "20"}
and I get "invalid json sent" from pingmeback.

**Comment by QuentinDeSoete** [comment]
In fact the problem was on my side.
I had a wrong usage of argparse and I found my solution here : 
http://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse

**Comment by yanc0** [comment]
Thank you for your feedback !
