### ISSUE TITLE
Missing error message when port is already used

### ISSUE THREAD

**Issue by tpoindessous** [yanc0/beeping#27]
Hi

I launched beeping as a simple user with this command `./beeping-v0.5.0 -listen 0.0.0.0` but port 8080 was already used.

Beeping didn't warn me with an error message and exit code was 0.

Thanks !

**Comment by tpoindessous** [comment]
same issue if `-listen` parameter is not a correct IP address for the computer.

Thanks!

**Comment by yanc0** [comment]
https://github.com/yanc0/beeping/blob/master/beeping.go#L166

ListenAndServe normally returns an error, but beeping don't catch it. It is a bug.
