### ISSUE TITLE
[FEATURE REQUEST] user can choose the listen port

### ISSUE THREAD

**Issue by tpoindessous** [yanc0/beeping#6]
Hi

can you, please, add an option so we can choose the listen port (8080) ?

Thanks.

**Comment by denisbr** [comment]
I wanted this too, but beeping is just using gin, so this will work:

```
PORT=9090 ./beeping
```

Alternatively: 

```
export PORT=1337
beeping
```

**Comment by yanc0** [comment]
Thanks you guys ! I've just added the port configuration in the README
