### ISSUE TITLE
External listener

### ISSUE THREAD

**Issue by TheHackerDev** [yanc0/beeping#9]
BeePing listens on port 8080 on _all interfaces_ (including the external interface) by default. 

<img width="709" alt="beeping global listener" src="https://cloud.githubusercontent.com/assets/2362857/25747382/4fe54adc-3175-11e7-8674-4d19673ec726.png">

I can submit a pull request if you'd like for the fix, but it's simply a matter of providing a specific IP and port combination to the `router.Run()` function. For example: `router.Run("127.0.0.1:8080")`. At the very least, people should be aware of it, so they aren't unknowingly opening up they internal network to enumeration by attackers ( #10 ) whenever they run a BeePing instance.

It's totally up to you, but I would suggest one of three fixes:

- Add a command-line option to accept local connections only. This is probably the most user-friendly, and depending on how you are using it at @skale-5, may fit your use case the best. **This is my recommended solution.**
- Set the router to listen locally automatically. This may not be how you wanted the program designed though, as it won't allow BeePing to run as an external-facing service.
- Notify users in the README.md file that BeePing listens on all interfaces by default. This way they are at least informed, and can adapt their firewall rules accordingly, if needed.

Cheers,
Aaron

**Comment by yanc0** [comment]
Thank you for your feedback !

I'll fix this on the next BeePing version (with a configuration system)

**Comment by TheHackerDev** [comment]
Great! Thanks, Yann.
